version = 1
name = "wallet-service-production"
uuid = "enclave_36c3d8ebf204"
app_uuid = "app_6e12fc400995"
team_uuid = "team_2cf986d8af8a"
debug = true
dockerfile = "./Dockerfile"
api_key_auth = true
trx_logging = true
tls_termination = true
forward_proxy_protocol = false
trusted_headers = []
healthcheck = "/api/v1/actions/HealthCheck"

[egress]
enabled = true
destinations = [
  "*.datadoghq.com",
  "app.dynamicauth.com",
  "app.dynamic.xyz",
  "mpc-relay.dynamic-prod.xyz"
]
