openapi: 3.0.3
info:
  title: Wallet Service API v1
  description: Securely provision and manage wallets
  version: 1.0.0
servers:
  - url: http://localhost:8010
    description: Local
paths:
  /api/v1/actions/HealthCheck:
    get:
      operationId: HealthCheck
      summary: Service Health Check
      description: Checks service health and availability
      x-eov-operation-handler: actions/HealthCheck
      responses:
        '200':
          description: Successfully revoked session key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
  /api/v1/actions/CreateWalletAccount:
    get:
      operationId: CreateWalletAccount
      summary: Create a wallet account
      description: Create a wallet account
      x-eov-operation-handler: actions/CreateWalletAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWalletAccountRequest'
      responses:
        '200':
          description: Successfully revoked session key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateWalletAccountResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    HealthCheckResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
    BadRequest:
      type: object
      properties:
        error_code:
          type: string
          enum:
            - bad_request
        error_message:
          type: string
    ThresholdSignatureScheme:
      type: string
      enum:
        - TWO_OF_TWO
        - TWO_OF_THREE
        - THREE_OF_FIVE
    CreateWalletAccountRequest:
      type: object
      required:
        - chainName
        - thresholdSignatureScheme
      properties:
        chainName:
          type: string
        thresholdSignatureScheme:
          $ref: '#/components/schemas/ThresholdSignatureScheme'
    CreateWalletAccountResponse:
      type: object
      required:
        - rawPublicKey
        - externalServerKeyGenResults
      properties:
        rawPublicKey:
          type: string
        externalServerKeyGenResults:
          type: string
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequest'
