openapi: 3.0.3
info:
  title: Wallet Service API v1
  description: Securely provision and manage wallets
  version: 1.0.0
servers:
  - url: http://localhost:8010
    description: Local
paths:
  /api/v1/actions/HealthCheck:
    get:
      operationId: HealthCheck
      summary: Service Health Check
      description: Checks service health and availability
      x-eov-operation-handler: actions/HealthCheck
      responses:
        '200':
          description: Successfully revoked session key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
  /api/v1/actions/CreateWalletAccount:
    post:
      operationId: CreateWalletAccount
      summary: Create a wallet account
      description: Create a wallet account
      x-eov-operation-handler: actions/CreateWalletAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWalletAccountRequest'
      responses:
        '200':
          description: Successfully created wallet account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateWalletAccountResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
  /api/v1/actions/SignMessage:
    post:
      operationId: SignMessage
      summary: Sign a message
      description: Sign a message
      x-eov-operation-handler: actions/SignMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignMessageRequest'
      responses:
        '200':
          description: Successfully signed message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignMessageResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
  /api/v1/actions/SignTransaction:
    post:
      operationId: SignTransaction
      summary: Sign a transaction
      description: Sign a transaction
      x-eov-operation-handler: actions/SignTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignTransactionRequest'
      responses:
        '200':
          description: Successfully signed transaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignTransactionResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
  /api/v1/actions/ImportPrivateKey:
    post:
      operationId: ImportPrivateKey
      summary: Import a private key
      description: Import a private key
      x-eov-operation-handler: actions/ImportPrivateKey
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImportPrivateKeyRequest'
      responses:
        '200':
          description: Successfully imported private key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportPrivateKeyResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    HealthCheckResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
    BadRequest:
      type: object
      properties:
        error_code:
          type: string
          enum:
            - bad_request
        error_message:
          type: string
    ThresholdSignatureScheme:
      type: string
      enum:
        - TWO_OF_TWO
        - TWO_OF_THREE
        - THREE_OF_FIVE
    CreateWalletAccountRequest:
      type: object
      required:
        - chainName
        - thresholdSignatureScheme
      properties:
        chainName:
          type: string
        thresholdSignatureScheme:
          $ref: '#/components/schemas/ThresholdSignatureScheme'
    CreateWalletAccountResponse:
      type: object
      required:
        - rawPublicKey
        - externalServerKeyGenResults
        - accountAddress
        - publicKeyHex
      properties:
        rawPublicKey:
          type: string
        externalServerKeyGenResults:
          type: string
        accountAddress:
          type: string
        publicKeyHex:
          type: string
    SignMessageRequest:
      type: object
      required:
        - chainName
        - message
        - accountAddress
      properties:
        chainName:
          type: string
        message:
          type: string
        accountAddress:
          type: string
        password:
          type: string
    SignMessageResponse:
      type: object
      required:
        - serializedSignature
      properties:
        serializedSignature:
          type: string
    SignTransactionRequest:
      type: object
      required:
        - chainName
        - sendToAddress
        - senderAddress
        - amount
        - sendRawTransaction
      properties:
        chainName:
          type: string
        sendToAddress:
          type: string
        senderAddress:
          type: string
        amount:
          type: string
        password:
          type: string
        sendRawTransaction:
          type: boolean
    SignTransactionResponse:
      type: object
      properties:
        signedTx:
          type: string
        txHash:
          type: string
        blockExplorerUrl:
          type: string
    ImportPrivateKeyRequest:
      type: object
      required:
        - chainName
        - privateKey
        - thresholdSignatureScheme
        - accountAddress
      properties:
        chainName:
          type: string
        privateKey:
          type: string
        accountAddress:
          type: string
        password:
          type: string
        thresholdSignatureScheme:
          type: string
    ImportPrivateKeyResponse:
      type: object
      required:
        - accountAddress
        - publicKeyHex
        - rawPublicKey
        - serverKeyShares
      properties:
        accountAddress:
          type: string
        publicKeyHex:
          type: string
        rawPublicKey:
          type: string
        serverKeyShares:
          type: string
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequest'
