openapi: 3.0.3
info:
  title: Wallet Service API v1
  description: Securely provision and manage wallets
  version: 1.0.0
servers:
  - url: http://localhost:8010
    description: Local
paths:
  /api/v1/actions/HealthCheck:
    get:
      operationId: HealthCheck
      summary: Service Health Check
      description: Checks service health and availability
      x-eov-operation-handler: actions/HealthCheck
      responses:
        '200':
          description: Successfully revoked session key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
  /api/v1/actions/{environmentId}/CreateWalletAccount:
    parameters:
      - $ref: '#/components/parameters/environmentId'
    post:
      operationId: CreateWalletAccount
      summary: Create a wallet account
      description: Create a wallet account
      x-eov-operation-handler: actions/CreateWalletAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWalletAccountRequest'
      responses:
        '200':
          description: Successfully created wallet account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateWalletAccountResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/v1/actions/{environmentId}/SignMessage:
    parameters:
      - $ref: '#/components/parameters/environmentId'
    post:
      operationId: SignMessage
      summary: Sign a message
      description: Sign a message
      x-eov-operation-handler: actions/SignMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignMessageRequest'
      responses:
        '200':
          description: Successfully signed message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignMessageResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/v1/actions/{environmentId}/SignTransaction:
    parameters:
      - $ref: '#/components/parameters/environmentId'
    post:
      operationId: SignTransaction
      summary: Sign a transaction
      description: Sign a transaction
      x-eov-operation-handler: actions/SignTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignTransactionRequest'
      responses:
        '200':
          description: Successfully signed transaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignTransactionResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/v1/actions/{environmentId}/ImportPrivateKey:
    parameters:
      - $ref: '#/components/parameters/environmentId'
    post:
      operationId: ImportPrivateKey
      summary: Import a private key
      description: Import a private key
      x-eov-operation-handler: actions/ImportPrivateKey
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImportPrivateKeyRequest'
      responses:
        '200':
          description: Successfully imported private key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportPrivateKeyResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
  /api/v1/actions/{environmentId}/GetWallets:
    parameters:
      - $ref: '#/components/parameters/environmentId'
    get:
      operationId: GetWallets
      summary: Get wallets
      description: Get wallets
      x-eov-operation-handler: actions/GetWallets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetWalletsRequest'
      responses:
        '200':
          description: Successfully retrieved wallets
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetWalletsResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/v1/actions/{environmentId}/ExportPrivateKey:
    parameters:
      - $ref: '#/components/parameters/environmentId'
    post:
      operationId: ExportPrivateKey
      summary: Export private key
      description: Export private key
      x-eov-operation-handler: actions/ExportPrivateKey
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExportPrivateKeyRequest'
      responses:
        '200':
          description: Successfully exported private key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExportPrivateKeyResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/v1/actions/{environmentId}/RefreshWalletShares:
    parameters:
      - $ref: '#/components/parameters/environmentId'
    post:
      operationId: RefreshWalletShares
      summary: Refresh wallet shares
      description: Refresh wallet shares
      x-eov-operation-handler: actions/RefreshWalletShares
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshWalletSharesRequest'
      responses:
        '200':
          description: Successfully refreshed wallet shares
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefreshWalletSharesResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  parameters:
    environmentId:
      name: environmentId
      in: path
      required: true
      description: ID of the environment
      example: 95b11417-f18f-457f-8804-68e361f9164f
      schema:
        type: string
        pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
        minLength: 36
        maxLength: 36
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    HealthCheckResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
    BadRequest:
      type: object
      properties:
        error_code:
          type: string
          enum:
            - bad_request
        error_message:
          type: string
    ThresholdSignatureScheme:
      type: string
      enum:
        - TWO_OF_TWO
        - TWO_OF_THREE
        - THREE_OF_FIVE
    CreateWalletAccountRequest:
      type: object
      required:
        - chainName
        - thresholdSignatureScheme
      properties:
        chainName:
          type: string
        thresholdSignatureScheme:
          $ref: '#/components/schemas/ThresholdSignatureScheme'
        password:
          type: string
    ExternalServerKeyShares:
      type: array
      items:
        type: object
        required:
          - pubkey
          - secretShare
        properties:
          pubkey:
            type: string
          secretShare:
            type: string
    CreateWalletAccountResponse:
      type: object
      required:
        - rawPublicKey
        - externalServerKeyShares
        - accountAddress
      properties:
        rawPublicKey:
          type: array
          items:
            type: integer
            format: uint8
          description: Raw public key as a Uint8Array
        externalServerKeyShares:
          $ref: '#/components/schemas/ExternalServerKeyShares'
        accountAddress:
          type: string
        publicKeyHex:
          type: string
    Forbidden:
      type: object
      required:
        - error_code
        - error_message
      properties:
        error_code:
          type: string
          enum:
            - api_key_required
            - api_key_invalid
            - api_key_not_authorized
        error_message:
          type: string
    InternalServerError:
      type: object
      properties:
        error_code:
          type: string
          enum:
            - internal_server_error
            - unknown_error
        error_message:
          type: string
          example: Internal Server Error
    SignMessageRequest:
      type: object
      required:
        - chainName
        - message
        - accountAddress
      properties:
        chainName:
          type: string
        message:
          type: string
        accountAddress:
          type: string
        password:
          type: string
    SignMessageResponse:
      type: object
      required:
        - serializedSignature
      properties:
        serializedSignature:
          type: string
    SignTransactionRequest:
      type: object
      required:
        - chainName
        - sendToAddress
        - senderAddress
        - amount
        - sendRawTransaction
      properties:
        chainName:
          type: string
        sendToAddress:
          type: string
        senderAddress:
          type: string
        amount:
          type: string
        password:
          type: string
        sendRawTransaction:
          type: boolean
    SignTransactionResponse:
      type: object
      properties:
        signedTx:
          type: string
        txHash:
          type: string
        blockExplorerUrl:
          type: string
    ImportPrivateKeyRequest:
      type: object
      required:
        - chainName
        - privateKey
        - thresholdSignatureScheme
        - accountAddress
      properties:
        chainName:
          type: string
        privateKey:
          type: string
        accountAddress:
          type: string
        password:
          type: string
        thresholdSignatureScheme:
          type: string
    ImportPrivateKeyResponse:
      type: object
      required:
        - accountAddress
        - rawPublicKey
        - externalServerKeyShares
      properties:
        rawPublicKey:
          type: array
          items:
            type: integer
            format: uint8
          description: Raw public key as a Uint8Array
        externalServerKeyShares:
          $ref: '#/components/schemas/ExternalServerKeyShares'
        accountAddress:
          type: string
        publicKeyHex:
          type: string
    GetWalletsRequest:
      type: object
      required:
        - chainName
      properties:
        chainName:
          type: string
    GetWalletsResponse:
      type: object
      required:
        - wallets
      properties:
        wallets:
          type: array
          items:
            type: object
            required:
              - walletId
              - chainName
              - accountAddress
            properties:
              walletId:
                type: string
              chainName:
                type: string
              accountAddress:
                type: string
              serverKeySharesBackupInfo:
                type: object
                additionalProperties: true
              externalServerKeyShares:
                type: array
                items:
                  type: string
              derivationPath:
                type: string
                nullable: true
              thresholdSignatureScheme:
                type: string
                nullable: true
    ExportPrivateKeyRequest:
      type: object
      required:
        - chainName
        - accountAddress
      properties:
        chainName:
          type: string
        accountAddress:
          type: string
        password:
          type: string
    ExportPrivateKeyResponse:
      type: object
      required:
        - derivedPrivateKey
      properties:
        derivedPrivateKey:
          type: string
    RefreshWalletSharesRequest:
      type: object
      required:
        - chainName
        - accountAddress
      properties:
        chainName:
          type: string
        accountAddress:
          type: string
        password:
          type: string
    RefreshWalletSharesResponse:
      type: object
      required:
        - externalServerKeyShares
      properties:
        externalServerKeyShares:
          type: array
          items:
            type: object
            required:
              - pubkey
              - secretShare
            properties:
              pubkey:
                type: string
              secretShare:
                type: string
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequest'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Forbidden'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternalServerError'
