openapi: 3.0.3
info:
  title: Wallet Service API v1
  description: Securely provision and manage wallets
  version: 1.0.0
servers:
  - url: http://localhost:8010
    description: Local
paths:
  /api/v1/actions/HealthCheck:
    $ref: paths/HealthCheck.yaml
  /api/v1/actions/{environmentId}/CreateWalletAccount:
    $ref: paths/CreateWalletAccount.yaml
  /api/v1/actions/{environmentId}/SignMessage:
    $ref: paths/SignMessage.yaml
  /api/v1/actions/{environmentId}/SignTransaction:
    $ref: paths/SignTransaction.yaml
  /api/v1/actions/{environmentId}/ImportPrivateKey:
    $ref: paths/ImportPrivateKey.yaml
  /api/v1/actions/{environmentId}/GetWallets:
    $ref: paths/GetWallets.yaml
components:
  parameters:
    environmentId:
      $ref: parameters/index.yaml#/environmentId
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
