# yaml-language-server: $schema='none'

name: Deploy
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: |
          npm ci
          npm run install:ev-enclave
      - name: Run tests
        run: npm test
      - name: Run Lint
        run: npm run lint
      - name: Check Types
        run: npm run build
  deploy-preprod:
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: preprod
      url: https://embedded-wallets-preprod.app-32d15525a875.enclave.evervault.com
    steps:
      - uses: actions/checkout@v4
      - name: Install ev
        run: npm run install:ev-enclave
      - name: Build & Deploy
        env:
          EV_API_KEY: ${{ secrets.EV_API_KEY }}
        run: |
          echo "${{ secrets.SIGNING_CERT }}" > /dev/shm/cert.pem
          echo "${{ secrets.SIGNING_KEY }}" > /dev/shm/key.pem
          ev-enclave deploy \
            --no-cache \
            --build-arg ENVIRONMENT=preproduction \
            --signing-cert /dev/shm/cert.pem \
            --private-key /dev/shm/key.pem \
            --config enclave.preprod.toml \
            --reproducible
          rm -f /dev/shm/cert.pem /dev/shm/key.pem
  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-preprod
    environment:
      name: production
      url: https://embedded-wallets-prod.app-6e12fc400995.enclave.evervault.com
    steps:
      - uses: actions/checkout@v4
      - name: Install ev
        run: npm run install:ev-enclave
      - name: Build & Deploy
        env:
          EV_API_KEY: ${{ secrets.EV_API_KEY }}
        run: |
          echo "${{ secrets.SIGNING_CERT }}" > /dev/shm/cert.pem
          echo "${{ secrets.SIGNING_KEY }}" > /dev/shm/key.pem
          ev-enclave deploy \
            --build-arg ENVIRONMENT=production \
            --no-cache \
            --signing-cert /dev/shm/cert.pem \
            --private-key /dev/shm/key.pem \
            --config enclave.prod.toml \
            --reproducible
          rm -f /dev/shm/cert.pem /dev/shm/key.pem
